### ISSUE TITLE
exported poll text

### ISSUE THREAD

**Issue by WahidinAji** [teknologi-umum/tgif#50]
the issue is when the message type is a question
```json
{
			"id": 632576,
			"type": "message",
			"date": "2024-02-25T11:53:31",
			"date_unixtime": "1708836811",
			"from": "Reinaldy",
			"from_id": "user1462097294",
			"poll": {
				"question": "Apakah Anda tahu kalau SSL certificate bisa digunakan selain untuk keperluan website (https)?",
				"closed": false,
				"total_voters": 25,
				"answers": [
					{
						"text": "Tahu",
						"voters": 11,
						"chosen": true
					},
					{
						"text": "Tidak",
						"voters": 14,
						"chosen": false
					}
				]
			},
			"text": "",
			"text_entities": []
		},
```
this doesn't show in the chat bubble card, just a blank chat bubble card
<img width="786" alt="image" src="https://github.com/teknologi-umum/tgif/assets/48281037/d75f8590-98b2-40e4-b8e1-cb8565c916c7">

**Comment by aldy505** [comment]
@elianiva @krowter Since this is not merely just a parsing issue, do either of you wanna work on this for the display side of things?

**Comment by aldy505** [comment]
@elianiva @krowter Since this is not merely just a parsing issue, do either of you wanna work on this for the display side of things?

**Comment by krowter** [comment]
@aldy505 Got it 👍
